#!/bin/bash
npm link ../material-components-web/packages/mdc-animation && \
npm link @material/animation && \
npm link ../material-components-web/packages/mdc-auto-init && \
npm link @material/auto-init && \
npm link ../material-components-web/packages/mdc-base && \
npm link @material/base && \
npm link ../material-components-web/packages/mdc-button && \
npm link @material/button && \
npm link ../material-components-web/packages/mdc-card && \
npm link @material/card && \
npm link ../material-components-web/packages/mdc-checkbox && \
npm link @material/checkbox && \
npm link ../material-components-web/packages/mdc-chips && \
npm link @material/chips && \
npm link ../material-components-web/packages/mdc-dialog && \
npm link @material/dialog && \
npm link ../material-components-web/packages/mdc-dom && \
npm link @material/dom && \
npm link ../material-components-web/packages/mdc-drawer && \
npm link @material/drawer && \
npm link ../material-components-web/packages/mdc-elevation && \
npm link @material/elevation && \
npm link ../material-components-web/packages/mdc-fab && \
npm link @material/fab && \
npm link ../material-components-web/packages/mdc-feature-targeting && \
npm link @material/feature-targeting && \
npm link ../material-components-web/packages/mdc-floating-label && \
npm link @material/floating-label && \
npm link ../material-components-web/packages/mdc-form-field && \
npm link @material/form-field && \
npm link ../material-components-web/packages/mdc-grid-list && \
npm link @material/grid-list && \
npm link ../material-components-web/packages/mdc-icon-button && \
npm link @material/icon-button && \
npm link ../material-components-web/packages/mdc-image-list && \
npm link @material/image-list && \
npm link ../material-components-web/packages/mdc-layout-grid && \
npm link @material/layout-grid && \
npm link ../material-components-web/packages/mdc-line-ripple && \
npm link @material/line-ripple && \
npm link ../material-components-web/packages/mdc-linear-progress && \
npm link @material/linear-progress && \
npm link ../material-components-web/packages/mdc-list && \
npm link @material/list && \
npm link ../material-components-web/packages/mdc-menu-surface && \
npm link @material/menu-surface && \
npm link ../material-components-web/packages/mdc-menu && \
npm link @material/menu && \
npm link ../material-components-web/packages/mdc-notched-outline && \
npm link @material/notched-outline && \
npm link ../material-components-web/packages/mdc-radio && \
npm link @material/radio && \
npm link ../material-components-web/packages/mdc-ripple && \
npm link @material/ripple && \
npm link ../material-components-web/packages/mdc-rtl && \
npm link @material/rtl && \
npm link ../material-components-web/packages/mdc-select && \
npm link @material/select && \
npm link ../material-components-web/packages/mdc-shape && \
npm link @material/shape && \
npm link ../material-components-web/packages/mdc-slider && \
npm link @material/slider && \
npm link ../material-components-web/packages/mdc-snackbar && \
npm link @material/snackbar && \
npm link ../material-components-web/packages/mdc-switch && \
npm link @material/switch && \
npm link ../material-components-web/packages/mdc-tab-bar && \
npm link @material/tab-bar && \
npm link ../material-components-web/packages/mdc-tab-indicator && \
npm link @material/tab-indicator && \
npm link ../material-components-web/packages/mdc-tab-scroller && \
npm link @material/tab-scroller && \
npm link ../material-components-web/packages/mdc-tab && \
npm link @material/tab && \
npm link ../material-components-web/packages/mdc-textfield && \
npm link @material/textfield && \
npm link ../material-components-web/packages/mdc-theme && \
npm link @material/theme && \
npm link ../material-components-web/packages/mdc-top-app-bar && \
npm link @material/top-app-bar && \
npm link ../material-components-web/packages/mdc-typography && \
npm link @material/typography
